version: "3.9"

services:
    backend:
        build: ./backend
        container_name:  backend
        restart: always
        expose:
            - 5000

    frontend:
        build: ./frontend
        container_name:  frontend
        tty: true
        restart: always
        ports:
            - "80:80"

